# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: around
